name: Build Image
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout jalno/base
        uses: actions/checkout@v4
        with:
          repository: jalno/base
          path: base

      - name: Checkout jalno/PhpParser
        uses: actions/checkout@v4
        with:
          repository: jalno/PhpParser
          path: base/packages/PhpParser

      - name: Checkout jalno/peeker
        uses: actions/checkout@v4
        with:
          repository: jalno/peeker
          path: base/packages/peeker

      - name: Checkout jalno/dockerize
        uses: actions/checkout@v4
        with:
          repository: jalno/dockerize
          path: base/packages/dockerize

      - run: cp base/packages/dockerize/.dockerignore base/.

      - name: Log into registry ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: base/packages/peeker/Dockerfile
          context: base/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
